// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHikpk9hSUFgROvXqTDqJz3xxhqB5TW_4',
    appId: '1:1098540645055:web:6fb4d2ce6cb23f0e39640a',
    messagingSenderId: '1098540645055',
    projectId: 'lkk-mobile',
    authDomain: 'lkk-mobile.firebaseapp.com',
    storageBucket: 'lkk-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCOvMhoCwSy-B8iVYDlBAcAX5AUAVGsVU',
    appId: '1:1098540645055:android:26c38014d46930cf39640a',
    messagingSenderId: '1098540645055',
    projectId: 'lkk-mobile',
    storageBucket: 'lkk-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS3U3xEG_KYp2zawZ94tyYmEk0XZU4RXY',
    appId: '1:1098540645055:ios:91164edee283475439640a',
    messagingSenderId: '1098540645055',
    projectId: 'lkk-mobile',
    storageBucket: 'lkk-mobile.appspot.com',
    iosClientId: '1098540645055-dqaf5f9bj3pjbsp8k3301im7nftm185r.apps.googleusercontent.com',
    iosBundleId: 'com.example.mkk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS3U3xEG_KYp2zawZ94tyYmEk0XZU4RXY',
    appId: '1:1098540645055:ios:91164edee283475439640a',
    messagingSenderId: '1098540645055',
    projectId: 'lkk-mobile',
    storageBucket: 'lkk-mobile.appspot.com',
    iosClientId: '1098540645055-dqaf5f9bj3pjbsp8k3301im7nftm185r.apps.googleusercontent.com',
    iosBundleId: 'com.example.mkk',
  );
}
