// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;

      default:
        return null;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsHvlARvfXtPKFbcm4y-soIL2pS8ua8xI',
    appId: '1:518583580460:web:0392a77316056dca6c9e89',
    messagingSenderId: '518583580460',
    projectId: 'puls--mobile-b2014',
    authDomain: 'puls--mobile-b2014.firebaseapp.com',
    storageBucket: 'puls--mobile-b2014.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9LqQfxR4uunGZ6_d9v7qLZ4ZPweEkhVA',
    appId: '1:518583580460:android:640b4304e687f8916c9e89',
    messagingSenderId: '518583580460',
    projectId: 'puls--mobile-b2014',
    storageBucket: 'puls--mobile-b2014.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXIcDEMVhmpaXHxbJi142_wbGA9zGZYPI',
    appId: '1:518583580460:ios:d771d1adb52109d96c9e89',
    messagingSenderId: '518583580460',
    projectId: 'puls--mobile-b2014',
    storageBucket: 'puls--mobile-b2014.appspot.com',
    androidClientId:
        '518583580460-ab5tl0s8bqntujrrhi690i4u0k54kr4l.apps.googleusercontent.com',
    iosClientId:
        '518583580460-4l2tvula72q6ke1ist4vptrfu9h4mumo.apps.googleusercontent.com',
    iosBundleId: 'com.mkk.release',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXIcDEMVhmpaXHxbJi142_wbGA9zGZYPI',
    appId: '1:518583580460:ios:d771d1adb52109d96c9e89',
    messagingSenderId: '518583580460',
    projectId: 'puls--mobile-b2014',
    storageBucket: 'puls--mobile-b2014.appspot.com',
    androidClientId:
        '518583580460-ab5tl0s8bqntujrrhi690i4u0k54kr4l.apps.googleusercontent.com',
    iosClientId:
        '518583580460-4l2tvula72q6ke1ist4vptrfu9h4mumo.apps.googleusercontent.com',
    iosBundleId: 'com.mkk.release',
  );
}
